// HISTORICAL DATA

export const HISTORICAL_DATA_LOADING = "HISTORICAL_DATA_LOADING";
export const HISTORICAL_DATA_LOADING_SUCCESS = "HISTORICAL_DATA_LOADING_SUCCESS";
export const HISTORICAL_DATA_LOADING_FAILURE = "HISTORICAL_DATA_LOADING_FAILURE";

export const HISTORICAL_DATA_SYMBOLS_LOADING = "FETCH_HISTORICAL_DATA_SYMBOLS_LOADING";
export const HISTORICAL_DATA_SYMBOLS_LOADING_SUCCESS = "FETCH_HISTORICAL_DATA_SYMBOLS_LOADING_SUCCESS";
export const HISTORICAL_DATA_SYMBOLS_LOADING_FAILURE = "FETCH_HISTORICAL_DATA_SYMBOLS_LOADING_FAILURE";

export const HISTORICAL_DATA_DATE_LIMITS_LOADING = "FETCH_HISTORICAL_DATA_DATE_LIMITS_LOADING";
export const HISTORICAL_DATA_DATE_LIMITS_LOADING_SUCCESS = "FETCH_HISTORICAL_DATA_DATE_LIMITS_LOADING_SUCCESS";
export const HISTORICAL_DATA_DATE_LIMITS_LOADING_FAILURE = "FETCH_HISTORICAL_DATA_DATE_LIMITS_LOADING_FAILURE";

// USER

export const REGISTERING_USER = "REGISTERING_USER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGGING_IN_USER = "LOGGING_IN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";

export const USER_PROFILE_LOADING = "USER_PROFILE_LOADING";
export const USER_PROFILE_LOAD_SUCCESS = "USER_PROFILE_LOAD_SUCCESS";
export const USER_PROFILE_LOAD_FAILURE = "USER_PROFILE_LOAD_FAILURE";

// PORTFOLIO

export const PORTFOLIO_HOLDINGS_LOADING = "PORTFOLIO_HOLDINGS_LOADING";
export const PORTFOLIO_HOLDINGS_LOADING_SUCCESS = "PORTFOLIO_HOLDINGS_LOADING_SUCCESS";
export const PORTFOLIO_HOLDINGS_LOADING_FAILURE = "PORTFOLIO_HOLDINGS_LOADING_FAILURE";

// ORDER

export const ORDER_PLACE_ORDER_SUCCESS = "ORDER_PLACE_ORDER_SUCCESS";
export const ORDER_PLACE_ORDER_FAILURE = "ORDER_PLACE_ORDER_FAILURE";
